import type { CatalogueItem, Slot } from "./types";

// Seed catalogue for the first region (Essex / Herts / London fringe), ordered by
// the Build Plan's supplier priority: décor/prop hire, furniture, lighting,
// stylists/florals, signage, mobile bars. Supplier names are illustrative.
// Prices are working estimates chosen so a styling-only look lands near the
// Build Plan's ~£2,600, rising to ~£4–5k once furniture and a bar are added.
//
// `image` points at an AI-generated catalogue photo in /public/img/items. Items
// without a photo fall back to the icon + swatch card (still fully bookable).
const IMG = "/img/items";

export const CATALOGUE: CatalogueItem[] = [
  // --- Ceremony backdrop (décor hire, "easy" catalogue) ---
  {
    id: "bd-moongate",
    name: "Circular Moongate Arch",
    slot: "ceremony_backdrop",
    supplier: "Willow & Co Prop Hire",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 320,
    unit: "each",
    qtyRule: "fixed",
    styles: ["garden_romance", "modern_minimal", "classic_elegance"],
    icon: "⛩️",
    swatch: "#c9a0a0",
    image: `${IMG}/bd-moongate.png`,
    rating: 4.9,
    reviewCount: 38,
    leadTimeDays: 30,
  },
  {
    id: "bd-rustic-arch",
    name: "Reclaimed Timber Arch",
    slot: "ceremony_backdrop",
    supplier: "Willow & Co Prop Hire",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 265,
    unit: "each",
    qtyRule: "fixed",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🪵",
    swatch: "#8a6f52",
    image: `${IMG}/bd-rustic-arch.png`,
    rating: 4.8,
    reviewCount: 52,
    leadTimeDays: 30,
  },
  {
    id: "bd-plinth-pair",
    name: "Ivory Plinth Pair",
    slot: "ceremony_backdrop",
    supplier: "Mono Event Studio",
    supplierArea: "St Albans, Herts",
    unitPrice: 180,
    unit: "pair",
    qtyRule: "fixed",
    styles: ["modern_minimal", "classic_elegance"],
    icon: "🏛️",
    swatch: "#d8c7ad",
    image: `${IMG}/bd-plinth-pair.jpg`,
    rating: 4.7,
    reviewCount: 19,
    leadTimeDays: 21,
  },

  // --- Centrepieces (per table) ---
  {
    id: "cp-foliage-runner",
    name: "Foliage Table Runner",
    slot: "centrepieces",
    supplier: "Fen & Fable Styling",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 48,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "garden_romance", "modern_minimal"],
    icon: "🌿",
    swatch: "#8a9a82",
    image: `${IMG}/cp-foliage-runner.png`,
    rating: 4.9,
    reviewCount: 64,
    leadTimeDays: 14,
  },
  {
    id: "cp-candelabra",
    name: "Gold Candelabra + Blooms",
    slot: "centrepieces",
    supplier: "Fen & Fable Styling",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 72,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🕯️",
    swatch: "#a67c52",
    image: `${IMG}/cp-candelabra.png`,
    rating: 4.8,
    reviewCount: 41,
    leadTimeDays: 14,
  },
  {
    id: "cp-stem-vase",
    name: "Single-Stem Vase Trio",
    slot: "centrepieces",
    supplier: "Mono Event Studio",
    supplierArea: "St Albans, Herts",
    unitPrice: 34,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["modern_minimal"],
    icon: "🌾",
    swatch: "#b0a99c",
    image: `${IMG}/cp-stem-vase.jpg`,
    rating: 4.6,
    reviewCount: 23,
    leadTimeDays: 14,
  },

  // --- Chairs (furniture hire, per guest) ---
  {
    id: "ch-crossback",
    name: "Oak Crossback Chair",
    slot: "chairs",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 6.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["rustic_barn", "garden_romance", "classic_elegance"],
    icon: "🪑",
    swatch: "#8a6f52",
    image: `${IMG}/ch-crossback.png`,
    rating: 4.9,
    reviewCount: 88,
    leadTimeDays: 45,
  },
  {
    id: "ch-chiavari",
    name: "Gold Chiavari Chair",
    slot: "chairs",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 5.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🪑",
    swatch: "#a67c52",
    image: `${IMG}/ch-chiavari.png`,
    rating: 4.7,
    reviewCount: 71,
    leadTimeDays: 45,
  },
  {
    id: "ch-bentwood",
    name: "Black Bentwood Chair",
    slot: "chairs",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 5.0,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["modern_minimal"],
    icon: "🪑",
    swatch: "#2b2622",
    image: `${IMG}/ch-bentwood.jpg`,
    rating: 4.6,
    reviewCount: 34,
    leadTimeDays: 45,
  },

  // --- Tables & linen (per table) ---
  {
    id: "tl-linen-natural",
    name: "Natural Slub Linen + Napkins",
    slot: "tables_linen",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 28,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "modern_minimal", "garden_romance"],
    icon: "🍽️",
    swatch: "#efe7db",
    image: `${IMG}/tl-linen-natural.jpg`,
    rating: 4.8,
    reviewCount: 46,
    leadTimeDays: 21,
  },
  {
    id: "tl-linen-ivory",
    name: "Ivory Damask Linen + Charger",
    slot: "tables_linen",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 39,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🍽️",
    swatch: "#f3ecdf",
    image: `${IMG}/tl-linen-ivory.jpg`,
    rating: 4.7,
    reviewCount: 29,
    leadTimeDays: 21,
  },

  // --- Lighting (per venue package) ---
  {
    id: "lt-festoon",
    name: "Festoon Canopy Package",
    slot: "lighting",
    supplier: "Lumen Wedding Lighting",
    supplierArea: "Brentwood, Essex",
    unitPrice: 540,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["rustic_barn", "garden_romance"],
    icon: "💡",
    swatch: "#d8c7ad",
    image: `${IMG}/lt-festoon.jpg`,
    rating: 4.9,
    reviewCount: 57,
    leadTimeDays: 60,
  },
  {
    id: "lt-fairy",
    name: "Fairy-Light Backdrop Wall",
    slot: "lighting",
    supplier: "Lumen Wedding Lighting",
    supplierArea: "Brentwood, Essex",
    unitPrice: 380,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["garden_romance", "classic_elegance", "rustic_barn"],
    icon: "✨",
    swatch: "#f3ecdf",
    image: `${IMG}/lt-fairy.jpg`,
    rating: 4.8,
    reviewCount: 43,
    leadTimeDays: 60,
  },
  {
    id: "lt-uplight",
    name: "Architectural Uplighting (x10)",
    slot: "lighting",
    supplier: "Lumen Wedding Lighting",
    supplierArea: "Brentwood, Essex",
    unitPrice: 300,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["modern_minimal", "classic_elegance"],
    icon: "🔦",
    swatch: "#b0a99c",
    image: `${IMG}/lt-uplight.jpg`,
    rating: 4.6,
    reviewCount: 22,
    leadTimeDays: 60,
  },

  // --- Florals (sold as packages, scaled per table — "hard" catalogue made easy) ---
  {
    id: "fl-garden-romance",
    name: "Garden Romance Floral Package",
    slot: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 95,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["garden_romance", "classic_elegance"],
    icon: "💐",
    swatch: "#d9b7ad",
    image: `${IMG}/fl-garden-romance.png`,
    rating: 5.0,
    reviewCount: 73,
    leadTimeDays: 90,
    note: "Includes ceremony arrangements + top-table run, priced per table.",
  },
  {
    id: "fl-wildflower",
    name: "Wildflower Meadow Package",
    slot: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 78,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🌸",
    swatch: "#c9a0a0",
    image: `${IMG}/fl-wildflower.png`,
    rating: 4.9,
    reviewCount: 61,
    leadTimeDays: 90,
  },
  {
    id: "fl-sculptural",
    name: "Sculptural Stem Package",
    slot: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 70,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["modern_minimal"],
    icon: "🪷",
    swatch: "#8a9a82",
    image: `${IMG}/fl-sculptural.jpg`,
    rating: 4.7,
    reviewCount: 18,
    leadTimeDays: 90,
  },

  // --- Signage (décor hire) ---
  {
    id: "sg-mirror",
    name: "Gold-Framed Welcome Mirror",
    slot: "signage",
    supplier: "Willow & Co Prop Hire",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 85,
    unit: "each",
    qtyRule: "fixed",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🪞",
    swatch: "#a67c52",
    image: `${IMG}/sg-mirror.jpg`,
    rating: 4.8,
    reviewCount: 27,
    leadTimeDays: 14,
  },
  {
    id: "sg-neon",
    name: "Custom Neon Sign",
    slot: "signage",
    supplier: "Mono Event Studio",
    supplierArea: "St Albans, Herts",
    unitPrice: 140,
    unit: "each",
    qtyRule: "fixed",
    styles: ["modern_minimal", "garden_romance"],
    icon: "🔆",
    swatch: "#d9b7ad",
    image: `${IMG}/sg-neon.jpg`,
    rating: 4.7,
    reviewCount: 31,
    leadTimeDays: 30,
  },

  // --- Mobile bar (medium difficulty, package pricing) ---
  {
    id: "bar-horsebox",
    name: "Horsebox Prosecco Bar",
    slot: "bar",
    supplier: "The Tipple Co Mobile Bars",
    supplierArea: "Colchester, Essex",
    unitPrice: 950,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🍾",
    swatch: "#b98a6a",
    image: `${IMG}/bar-horsebox.png`,
    rating: 4.9,
    reviewCount: 49,
    leadTimeDays: 120,
  },
  {
    id: "bar-copper",
    name: "Copper-Top Cocktail Bar",
    slot: "bar",
    supplier: "The Tipple Co Mobile Bars",
    supplierArea: "Colchester, Essex",
    unitPrice: 1150,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["classic_elegance", "modern_minimal"],
    icon: "🍸",
    swatch: "#a67c52",
    image: `${IMG}/bar-copper.png`,
    rating: 4.8,
    reviewCount: 36,
    leadTimeDays: 120,
  },
];

export const SLOT_META: {
  slot: Slot;
  label: string;
  optional: boolean;
  blurb: string;
}[] = [
  {
    slot: "ceremony_backdrop",
    label: "Ceremony backdrop",
    optional: false,
    blurb: "The focal point you'll say 'I do' in front of.",
  },
  {
    slot: "florals",
    label: "Florals",
    optional: false,
    blurb: "Arrangements for the aisle, top table and centrepieces.",
  },
  {
    slot: "centrepieces",
    label: "Centrepieces",
    optional: false,
    blurb: "What sits on each guest table.",
  },
  {
    slot: "chairs",
    label: "Chairs",
    optional: false,
    blurb: "One per guest, delivered and set up.",
  },
  {
    slot: "tables_linen",
    label: "Tables & linen",
    optional: false,
    blurb: "Linen, napkins and place settings per table.",
  },
  {
    slot: "lighting",
    label: "Lighting",
    optional: false,
    blurb: "Transforms the room once the sun goes down.",
  },
  {
    slot: "signage",
    label: "Signage",
    optional: true,
    blurb: "Welcome signs and personal touches.",
  },
  {
    slot: "bar",
    label: "Mobile bar",
    optional: true,
    blurb: "A statement bar for drinks and cocktails.",
  },
];

export function slotMeta(slot: Slot) {
  return SLOT_META.find((s) => s.slot === slot)!;
}

export function itemsForSlot(slot: Slot): CatalogueItem[] {
  return CATALOGUE.filter((i) => i.slot === slot);
}

export function getItem(id: string): CatalogueItem | undefined {
  return CATALOGUE.find((i) => i.id === id);
}
